sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dockerdec1981/docker-react -f Dockerfile.dev .

script:
  - docker run dockerdec1981/docker-react npm run test -- --coverage
